/* $Id: en.js,v 1.4 2009/10/27 20:15:55 wvankuipers Exp $ */
tinyMCE.addI18n('en.Archiv',{
	Fdesc : "Insert a file",
	Idesc : "Insert a image",
	ErrorLoadingTree: "Error loading filetree!",
	NoFiles : "This directory does not contain any files!",
	ErrorLoadingDirContent : "Error loading dir content!",
	FileDelete : "Delete file",
	FileName: "Name",
	FileType: "Type",
	FileSize: "Size",
	FileDimentions: "Dimentions",
	FileInfo : "File info",
	FileClickToAdd: "Click to add",
	ErrorAddingDirectory : "Error adding directory!",
	ErrorDeletingFile : "Error deleting file!",
	ErrorDeletingDirectory : "Error deleting directory!",
	QuestionDirectoryName : "Please enter a name for the directory",
	QuestionPassword : "Please enter your password",
	ErrorReadingSettingsFile : "Error reading the config!",
	ConfirmDeleteFile : "Are you sure you whish to delete the file",
	ConfirmDeleteDirectory : "Are you sure you whish to delete the directory",
	ErrorOldFlashVersion: "Your flash version is out of date or not installed",	
	PleaseUpdateFlashVersion: "please update to the latest version",
	FileDeleted: "File deleted",
	DirectoryDeleted: "Directory deleted",
	FatalError: "Error, please restart the filemanager!",
	ErrorToManyFiles: "You have attempted to queue too many files",
	CreatingThumbnail: "Creating thumbnail",
	Uploading: "Uploading",
	AllImagesReceived: "All images received",
	AllFilesReceived: "All files received"
});
