/* $Id: es.js,v 1.3 2009/10/27 20:15:55 wvankuipers Exp $ */
tinyMCE.addI18n('es.Archiv',{
	Fdesc : "Insertar un archivo",
	Idesc : "Insertar una imagen",
	ErrorLoadingTree: "Error cargando lista de carpetas!",
	NoFiles : "Esta carpeta no contiene archivos!",
	ErrorLoadingDirContent : "Error cargando contenido de la carpeta!",
	FileDelete : "Eliminar archivo",
	FileName: "Nombre",
	FileType: "Tipo",
	FileSize: "Tama&ntilde;o",
	FileDimentions: "Dimensiones",
	FileInfo : "Informacion del archivo",
	FileClickToAdd: "Click para agregar",
	ErrorAddingDirectory : "Error agregando carpeta!",
	ErrorDeletingFile : "Error borrando archivo!",
	ErrorDeletingDirectory : "Error borrando carpeta!",
	QuestionDirectoryName : "Ingrese un nombre para la carpeta",
	QuestionPassword : "Ingresse su contrase&ntilde;a",
	ErrorReadingSettingsFile : "Error leyendo config!",
	ConfirmDeleteFile : "Esta seguro de querer borrar el archivo",
	ConfirmDeleteDirectory : "Esta seguro de querer borrar la carpeta",
	ErrorOldFlashVersion: "No se ha instalado el Plugin Flash o no está actualizado",
	PleaseUpdateFlashVersion: "por favor actualiza a la ultima versión",
	FileDeleted: "Archivo eliminado",
	DirectoryDeleted: "Directory deleted",
	FatalError: "Error, por favor reinicia el administrador!",
	ErrorToManyFiles: "Has intentado subir demasiados archivos",
	CreatingThumbnail: "Creando imagen miniatura",
	Uploading: "Subiendo",
	AllImagesReceived: "Se recibieron todas las imagenes",
	AllFilesReceived: "All files received"	
});
