/* $Id: fr.js,v 1.3 2009/10/27 20:15:55 wvankuipers Exp $ */
tinyMCE.addI18n('fr.Archiv',{
	Fdesc : "Ins�rer un fichier",
	Idesc : "Ins�rer une image",
	ErrorLoadingTree: "Erreur lors de la lecture de la structure du dossier!",
	NoFiles : "Ce dossier ne contient aucun fichier!",
	ErrorLoadingDirContent : "Erreur lors du chargement du contenu du dossier!",
	FileDelete : "Supprimmer fichier",
	FileName: "Nom",
	FileType: "Type",
	FileSize: "Taille",
	FileDimentions: "Dimenssions",
	FileInfo : "Info de Fichier",
	FileClickToAdd: "Cliquer pour ajouter",
	ErrorAddingDirectory : "Erreur lors de l\'ajout du dossier!",
	ErrorDeletingFile : "Erreur lors de la suppression du fichier!",
	ErrorDeletingDirectory : "Erreur lors de la suppression du dossier!",
	QuestionDirectoryName : "Merci d\'entrer un nom pour le dossier",
	QuestionPassword : "Merci d'entrer votre mot de passe",
	ErrorReadingSettingsFile : "Erreur lors de la lecture de la configuration!",
	ConfirmDeleteFile : "Etes vous s�re de vouloir supprimmer ce fichier",
	ConfirmDeleteDirectory : "Etes vous s�re de vouloir supprimmer ce dossier",
	ErrorOldFlashVersion: "Your flash version is out of date or not installed",	
	PleaseUpdateFlashVersion: "please update to the latest version",
	FileDeleted: "File deleted",
	DirectoryDeleted: "Directory deleted",
	FatalError: "Error, please restart the filemanager!",
	ErrorToManyFiles: "You have attempted to queue too many files",
	CreatingThumbnail: "Creating thumbnail",
	Uploading: "Uploading",
	AllImagesReceived: "All images received",
	AllFilesReceived: "All files received"	
});
