/* $Id: nl.js,v 1.4 2009/10/27 20:15:55 wvankuipers Exp $ */
tinyMCE.addI18n('nl.Archiv',{
	Fdesc : "Voeg een bestand toe",
	Idesc : "Voeg een afbeelding toe",
	ErrorLoadingTree: "Error bij het aanmaken van de mappenlijst!",
	NoFiles : "Deze map bevat nog geen bestanden!",
	ErrorLoadingDirContent : "Error bij het laden van de mapinhoud!",
	FileDelete : "Bestand verwijderen",
	FileName: "Naam",
	FileType: "Type",
	FileSize: "Grootte",
	FileDimentions: "Afmetingen",
	FileInfo : "Bestandsinformatie",
	FileClickToAdd: "Klik om toe te voegen",
	ErrorAddingDirectory : "Error bij het aanmaken van de map!",
	ErrorDeletingFile : "Error bij het verwijderen van het bestand!",
	ErrorDeletingDirectory : "Error bij het verwijderen van de map!",
	QuestionDirectoryName : "Geef een naam voor de nieuwe map",
	QuestionPassword : "Geef uw wachtwoord",
	ErrorReadingSettingsFile : "Error bij het lezen van de config!",
	ConfirmDeleteFile : "Weet u zeker dat u dit bestand wilt verwijderen",
	ConfirmDeleteDirectory : "Weet u zeker dat u deze map wilt verwijderen",
	ErrorOldFlashVersion: "Flash versie verouderd of niet gevonden",	
	PleaseUpdateFlashVersion: "update a.u.b. uw flash versie",
	FileDeleted: "Bestand verwijderd",
	DirectoryDeleted: "Map verwijderd",
	FatalError: "Error, herstart de filemanager!",
	ErrorToManyFiles: "YJe hebt teveel bestanden geselecteerd",
	CreatingThumbnail: "Bezig met het genereren van de thumbnail",
	Uploading: "Uploading",
	AllImagesReceived: "Alle afbeeldingen ontvangen",
	AllFilesReceived: "AAlle bestanden ontvangen"	
});
