changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🛠 Breaking Changes 
      labels:
        - Breaking-Change
    - title: 🎉 New Features 
      labels:
        - Feature
    - title: 🐞 Bug Fixes
      labels:
        - Bug
    - title: Other Changes
      labels:
        - "*"
