name: Feature request
description: Suggest an idea for this project.
title: "[Feature]: "
labels: ["Feature"]
assignees: 
  - marcelfolaron
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to submit a feature request. If you have problems with the installation or other questions please use the [discussion forum](https://github.com/Leantime/leantime/discussions) or our [discord server](https://discord.gg/4zMzJtAq9z)"
  - type: dropdown
    attributes:
      label: What is your set up? 
      options:
        - Cloud Hosted
        - Self Hosted Server
        - Self Hosted Docker
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. 
      placeholder: Ex. I'm always frustrated when [...]
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
    validations:
