FROM php:8.1-apache
COPY ./dev-apache2.conf /etc/apache2/apache2.conf
COPY ./dev-ports.conf /etc/apache2/ports.conf
RUN a2enmod rewrite
RUN apt update && apt install -f -y  libonig-dev libcurl4-openssl-dev libxml2-dev \
    libxslt1-dev  libzip-dev libjson-c-dev libldap-dev libargon2-dev \
    libfreetype6-dev libjpeg62-turbo-dev libpng-dev
RUN  docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) pdo_mysql ldap  gd
COPY ./dev-apache-site.conf /etc/apache2/sites-enabled/000-default.conf
