<?php  //[STAMP] ccb178f6da210ae20ebdcc25e45ff6a2
// phpcs:ignoreFile
namespace Tests\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
