name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "master", "*.*-dev" ]
  pull_request:
    branches: [ "master", "*.*-dev" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: redis, gd, ldap, mbstring, pdo_mysql, zip, bcmath, exif, pcntl

    - name: Install dependencies
      run: make build

    - name: Run distcheck
      run: make clean
