name: Static Analysis

on:
  workflow_dispatch:
  push:
    branches: [ "master", "*.*-dev" ]
  pull_request:
    branches: [ "master", "*.*-dev" ]

jobs:
  phpstan:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: redis, gd, ldap, mbstring, pdo_mysql, zip, bcmath, exif, pcntl

    - name: Install Dependencies
      run: make build-dev

    # Use a warm PHPStan result cache when possible to speedup analysis
    - name: "Restore PHPStan result cache"
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: "/tmp/phpstan"
        key: "result-cache-v1-${{ env.PHP_VERSION }}-${{ github.run_id }}"
        restore-keys: |
          result-cache-v1-${{ env.PHP_VERSION }}-      

    - name: Run PHPStan Analysis
      run: make phpstan

    # Persist the PHPStan cache for re-use on the next run
    - name: "Save result cache"
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      if: ${{ !cancelled() }}
      with:
        path: "/tmp/phpstan"
        key: "result-cache-v1-${{ env.PHP_VERSION }}-${{ github.run_id }}"
